#!/usr/bin/env python3
"""Shell-shape comparison harness.

For each species in ``species.json``:
  1. get the mesh from the Rust core *through the existing wasm* — the same
     ``generate(params)`` the web page calls — via the Node bridge
     ``extract_mesh.mjs`` (no Rust code is touched, nothing is rebuilt);
  2. build a Wavefront OBJ from the returned arrays here in Python;
  3. render it offscreen with pyvista from a canonical "spire-up" pose;
  4. write ``report.html`` pairing each render with the real reference photo,
     so a human can scan for shapes that don't match.

Usage:
    python render_catalog.py                 # all species
    python render_catalog.py --only conus-marmoreus auger ...
    python render_catalog.py --size 640
"""
from __future__ import annotations

import argparse
import json
import os
import struct
import subprocess
import sys
import tempfile
from html import escape
from pathlib import Path

import numpy as np
import pyvista as pv

HERE = Path(__file__).resolve().parent
BRIDGE = HERE / "extract_mesh.mjs"
SPECIES_JSON = HERE / "species.json"
REF_DIR = HERE / "reference"
MESH_DIR = HERE / "meshes"
OUT_DIR = HERE / "rendered"
REPORT = HERE / "report.html"

SHELL_COLOR = "#e7d8b6"  # warm cream, neutral so shape (not colour) is judged
COVERAGE_COLOR = {"good": "#3fa45b", "silhouette": "#c8a35a", "blocked": "#c0524a"}


# ----------------------------------------------------------------------------- mesh
def get_mesh(params: dict) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Run the Node bridge and decode its binary mesh stream → (pos, nor, idx)."""
    proc = subprocess.run(
        ["node", str(BRIDGE), json.dumps(params)], capture_output=True
    )
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.decode() or "extract_mesh.mjs failed")
    b = proc.stdout
    n_pos, n_nor, n_uv, n_idx = struct.unpack_from("<4I", b, 0)
    off = 16
    pos = np.frombuffer(b, np.float32, n_pos, off).reshape(-1, 3); off += n_pos * 4
    nor = np.frombuffer(b, np.float32, n_nor, off).reshape(-1, 3); off += n_nor * 4
    off += n_uv * 4  # uvs unused for rendering
    idx = np.frombuffer(b, np.uint32, n_idx, off).reshape(-1, 3)
    return pos, nor, idx


def write_obj(path: Path, pos: np.ndarray, nor: np.ndarray, idx: np.ndarray) -> None:
    """Generate a Wavefront OBJ (the OBJ is built here in Python, not in Rust)."""
    chunks = ["# generated by harness/render_catalog.py\n"]
    chunks.append("\n".join(f"v {x:.6g} {y:.6g} {z:.6g}" for x, y, z in pos))
    chunks.append("\n" + "\n".join(f"vn {x:.5g} {y:.5g} {z:.5g}" for x, y, z in nor))
    f = idx + 1  # OBJ is 1-indexed
    chunks.append("\n" + "\n".join(f"f {a}//{a} {b}//{b} {c}//{c}" for a, b, c in f))
    path.write_text("".join(chunks))


# --------------------------------------------------------------------------- render
def render(obj_path: Path, png_path: Path, size: int, t: float) -> None:
    """Render the OBJ offscreen in a canonical pose.

    The generator orients the coil axis to +Y, the pointed apex to -Y, and the
    body whorl/aperture toward +Z. The model is a *hollow* swept tube (no
    columella), so looking into the aperture (+Z) shows the cavity. We therefore
    view spired shells from the dorsal (abapertural, -Z) side at a 3/4 angle with
    the spire up, which shows the solid convex form; planispirals (T~0) have no
    spire, so we look face-on down the coil axis to show the coil.
    """
    mesh = pv.read(obj_path)
    pl = pv.Plotter(off_screen=True, window_size=[size, size])
    pl.set_background("white")
    pl.add_mesh(
        mesh, color=SHELL_COLOR, smooth_shading=True,
        ambient=0.25, diffuse=0.75, specular=0.35, specular_power=18,
    )
    center = np.asarray(mesh.center)
    pl.camera.focal_point = center
    if t < 0.15:  # planispiral — view the coil face-on, down the +Y axis
        pl.camera.up = (0.0, 0.0, -1.0)
        pl.camera.position = center + np.array([0.0, 1.0, 0.0])
    else:  # spired — dorsal 3/4 view, apex (-Y) up
        pl.camera.up = (0.0, -1.0, 0.0)
        pl.camera.position = center + np.array([0.4, 0.0, -1.0])
    pl.reset_camera()       # fit distance to bounds, keeping direction + up
    pl.camera.zoom(1.35)
    pl.screenshot(str(png_path))
    pl.close()


# --------------------------------------------------------------------------- report
def coverage_chip(cov: str) -> str:
    color = COVERAGE_COLOR.get(cov, "#777")
    return (f'<span class="chip" style="background:{color}">{escape(cov)}</span>')


def build_report(rows: list[dict]) -> None:
    counts = {"good": 0, "silhouette": 0, "blocked": 0}
    for r in rows:
        counts[r["coverage"]] = counts.get(r["coverage"], 0) + 1
    bar = " · ".join(
        f'<b style="color:{COVERAGE_COLOR[k]}">{v} {k}</b>' for k, v in counts.items()
    )

    cards = []
    for r in rows:
        ref = REF_DIR / Path(r["reference"]).name if r.get("reference") else None
        ref_html = (
            f'<img src="reference/{escape(ref.name)}" alt="reference">'
            if ref and ref.exists()
            else '<div class="missing">no reference photo<br>'
            f'<small>{escape(r.get("reference",""))}</small></div>'
        )
        render_html = (
            f'<img src="rendered/{escape(r["slug"])}.png" alt="render">'
            if r.get("ok")
            else f'<div class="missing err">render failed<br><small>{escape(r.get("error",""))}</small></div>'
        )
        src = r.get("reference_source", "")
        src_html = f'<a href="{escape(src)}" target="_blank">photo source</a>' if src else ""
        cards.append(f"""
      <div class="card">
        <div class="head">
          <span class="sci">{escape(r["scientific"])}</span>
          <span class="com">{escape(r.get("common",""))} · {escape(r.get("family",""))}</span>
          {coverage_chip(r["coverage"])}
        </div>
        <div class="pair">
          <figure>{ref_html}<figcaption>real shell {src_html}</figcaption></figure>
          <figure>{render_html}<figcaption>generated</figcaption></figure>
        </div>
        <p class="notes">{escape(r.get("notes",""))}</p>
        <pre class="params">{escape(json.dumps(r["params"]))}</pre>
      </div>""")

    html = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>Shell catalog — generated vs. real</title>
<style>
  :root {{ color-scheme: light; }}
  body {{ margin:0; font:14px/1.5 system-ui,sans-serif; background:#f4f1ea; color:#23272e; }}
  header {{ padding:18px 24px; border-bottom:1px solid #e0dccf; background:#fbf9f3; position:sticky; top:0; }}
  h1 {{ margin:0 0 4px; font-size:18px; }}
  .sub {{ color:#777; font-size:12px; }}
  .grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(440px,1fr)); gap:18px; padding:24px; }}
  .card {{ border:1px solid #e0dccf; border-radius:10px; background:#fff; overflow:hidden; }}
  .head {{ display:flex; align-items:baseline; gap:8px; flex-wrap:wrap; padding:10px 14px; border-bottom:1px solid #efece2; }}
  .sci {{ font-weight:600; font-style:italic; }}
  .com {{ color:#888; font-size:12px; flex:1; }}
  .chip {{ color:#fff; font-size:10px; text-transform:uppercase; letter-spacing:.04em; padding:2px 7px; border-radius:10px; }}
  .pair {{ display:grid; grid-template-columns:1fr 1fr; }}
  figure {{ margin:0; }}
  figure img, .missing {{ width:100%; aspect-ratio:1; object-fit:cover; display:block; background:#faf8f2; }}
  .missing {{ display:flex; flex-direction:column; align-items:center; justify-content:center; color:#aaa; text-align:center; }}
  .missing.err {{ color:#c0524a; }}
  figcaption {{ font-size:11px; color:#999; text-align:center; padding:4px; }}
  .notes {{ margin:0; padding:10px 14px; font-size:12px; color:#555; }}
  .params {{ margin:0; padding:8px 14px 12px; font-size:11px; color:#999; white-space:pre-wrap; word-break:break-all; }}
  a {{ color:#b07a2a; }}
</style></head><body>
<header><h1>Shell catalog — generated vs. real</h1>
<div class="sub">{len(rows)} species · {bar} · meshes from the Rust core via web/pkg wasm</div></header>
<div class="grid">{''.join(cards)}</div>
</body></html>"""
    REPORT.write_text(html)


# ----------------------------------------------------------------------------- main
def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--only", nargs="*", help="render only these slugs (substring match)")
    ap.add_argument("--size", type=int, default=560, help="render size in px")
    ap.add_argument("--keep-obj", action="store_true",
                    help="persist each OBJ in meshes/ (large) instead of a temp file")
    args = ap.parse_args()

    pv.OFF_SCREEN = True
    OUT_DIR.mkdir(exist_ok=True)
    if args.keep_obj:
        MESH_DIR.mkdir(exist_ok=True)

    species = json.loads(SPECIES_JSON.read_text())
    if args.only:
        species = [s for s in species if any(k in s["slug"] for k in args.only)]

    rows = []
    for i, sp in enumerate(species, 1):
        slug = sp["slug"]
        print(f"[{i}/{len(species)}] {slug} … ", end="", flush=True)
        row = dict(sp, ok=False)
        try:
            pos, nor, idx = get_mesh(sp["params"])
            # Build the OBJ here in Python. Keep it only with --keep-obj (the OBJ
            # text is large); otherwise render from a temp file and discard it.
            if args.keep_obj:
                obj, tmp = MESH_DIR / f"{slug}.obj", None
            else:
                fd, tmp = tempfile.mkstemp(suffix=".obj")
                os.close(fd)
                obj = Path(tmp)
            write_obj(obj, pos, nor, idx)
            render(obj, OUT_DIR / f"{slug}.png", args.size, float(sp["params"].get("t", 1.5)))
            if tmp:
                obj.unlink(missing_ok=True)
            row["ok"] = True
            print(f"{len(pos)} verts ✓")
        except Exception as e:  # keep going; the report shows the failure
            row["error"] = str(e)
            print(f"FAILED: {e}", file=sys.stderr)
        rows.append(row)

    build_report(rows)
    missing = [r["slug"] for r in rows if r.get("reference") and not (REF_DIR / Path(r["reference"]).name).exists()]
    if missing:
        print(f"\n{len(missing)} species missing reference photos: {', '.join(missing)}")
    print(f"\nReport: {REPORT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
