//! Pure mesh generation for spiral shells.
//!
//! Layer-1 coiling geometry only (see `parameters.md`): a single tube swept
//! along a logarithmic helico-spiral. Ornamentation / pigment / colour are not
//! handled here — they hook in later by modulating the aperture in `generate`.
//!
//! No JS/wasm dependencies, so this crate is unit-testable with plain `cargo test`.

use serde::{Deserialize, Serialize};
use std::f32::consts::PI;

/// Layer-1 coiling parameters (Raup W/D/T + practical extras).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShellParams {
    /// Whorl expansion rate per revolution (> 1). Snails ~1.1–3, Nautilus ~3.
    pub w: f32,
    /// Openness: 0 = whorls touch the axis (tight), → 1 = open coil / wide umbilicus.
    pub d: f32,
    /// Translation rate along the axis. 0 = planispiral (flat), higher = tall spire.
    pub t: f32,
    /// Number of whorls (revolutions).
    pub n: f32,
    /// Aperture aspect ratio (radial semi-axis / axial semi-axis). 1 = circular tube.
    #[serde(default = "default_aspect")]
    pub aspect: f32,

    // --- Layer 2: rib / wave ornamentation (see parameters.md) ---
    /// Axial ribs/waves: number across the whorl, per revolution.
    #[serde(default)]
    pub rib_ax_count: f32,
    /// Axial amplitude as a fraction of tube radius. High = structural wave.
    #[serde(default)]
    pub rib_ax_amp: f32,
    /// Spiral cords: number around the aperture cross-section.
    #[serde(default)]
    pub rib_sp_count: f32,
    /// Spiral amplitude as a fraction of tube radius.
    #[serde(default)]
    pub rib_sp_amp: f32,
    /// Profile: 0 = smooth sine wave, 1 = sharp knife-edge ridge.
    #[serde(default)]
    pub rib_sharp: f32,

    // --- projections: the nodule → spine continuum ---
    /// Projections per whorl (count along the coil). 0 = none.
    #[serde(default)]
    pub proj_count: f32,
    /// Rows of projections around the aperture. 1 = single row (spine-like),
    /// ≥2 = evenly spaced rows (nodulose).
    #[serde(default)]
    pub proj_rows: f32,
    /// Position of the first row around the aperture, radians (0..2π).
    #[serde(default)]
    pub proj_pos: f32,
    /// Projection size (height/length) as a fraction of tube radius.
    #[serde(default)]
    pub proj_size: f32,
    /// Sharpness: 0 = rounded blunt bead (nodule), 1 = narrow needle (spine).
    #[serde(default)]
    pub proj_sharp: f32,

    // --- varices ---
    /// Varices (prominent transverse ridges) per whorl. 0 = none.
    #[serde(default)]
    pub varix_count: f32,
    /// Varix prominence as a fraction of tube radius.
    #[serde(default)]
    pub varix_amp: f32,

    // --- randomness (seeded → reproducible) ---
    /// Random seed (integer-valued). Same seed + params → identical shape.
    #[serde(default)]
    pub seed: f32,
    /// Randomness amount, 0..1. 0 = perfectly uniform (seed has no effect).
    #[serde(default)]
    pub jitter: f32,

    // --- Layer 3: pigmentation (reaction–diffusion at the growing lip) ---
    // The shell's colour pattern is laid down by the mantle edge at the growing
    // aperture, so it is generated by the *same* growth sweep as the geometry: a
    // 1-D reaction–diffusion line runs around the lip (φ) and is stepped once per
    // growth ring (θ). See `pigment_field`.
    /// Pattern regime (integer index into `PIGMENT_RANGES` / `PigRegime`):
    /// 0=solid, 1=spiral bands, 2=axial stripes, 3=oblique lines,
    /// 4=chevrons/tented, 5=spots, 6=reticulated. Selects the RD configuration.
    #[serde(default)]
    pub pig_regime: f32,
    /// Feature scale: small = fine/many features, large = coarse/few. 0..1.
    #[serde(default = "default_pig_scale")]
    pub pig_scale: f32,
    /// Contrast: soft gradient (0) → crisp hard-edged pattern (1). 0..1.
    #[serde(default = "default_pig_contrast")]
    pub pig_contrast: f32,
    /// Feature density along the coil (reaction speed → spacing over growth). 0..1.
    #[serde(default = "default_pig_density")]
    pub pig_density: f32,
    /// Obliqueness: travelling-wave drift around the lip → diagonal lean. 0..1.
    #[serde(default)]
    pub pig_angle: f32,
    /// Irregularity: seeded noise in the pattern (0 = perfectly regular). 0..1.
    #[serde(default)]
    pub pig_irregularity: f32,

    /// Tessellation: segments per revolution along the coil.
    #[serde(default = "default_seg_theta")]
    pub seg_theta: u32,
    /// Tessellation: segments around the aperture cross-section.
    #[serde(default = "default_seg_phi")]
    pub seg_phi: u32,
}

fn default_aspect() -> f32 {
    1.0
}
fn default_pig_scale() -> f32 {
    0.5
}
fn default_pig_contrast() -> f32 {
    0.5
}
fn default_pig_density() -> f32 {
    0.5
}
fn default_seg_theta() -> u32 {
    96
}
fn default_seg_phi() -> u32 {
    48
}

impl Default for ShellParams {
    fn default() -> Self {
        Self {
            w: 2.0,
            d: 0.15,
            t: 1.5,
            n: 5.0,
            aspect: 1.0,
            rib_ax_count: 0.0,
            rib_ax_amp: 0.0,
            rib_sp_count: 0.0,
            rib_sp_amp: 0.0,
            rib_sharp: 0.0,
            proj_count: 0.0,
            proj_rows: 0.0,
            proj_pos: 0.0,
            proj_size: 0.0,
            proj_sharp: 0.0,
            varix_count: 0.0,
            varix_amp: 0.0,
            seed: 0.0,
            jitter: 0.0,
            pig_regime: 0.0,
            pig_scale: 0.5,
            pig_contrast: 0.5,
            pig_density: 0.5,
            pig_angle: 0.0,
            pig_irregularity: 0.0,
            seg_theta: 96,
            seg_phi: 48,
        }
    }
}

/// Metadata for one user-facing shape parameter — the single source of truth
/// for its valid range, slider configuration, and clamping behaviour.
///
/// The web UI reads this table (via the wasm `param_ranges()` export) to
/// configure its sliders, and `generate` clamps every input to it, so a value
/// can never be out of range regardless of where it came from.
#[derive(Debug, Clone, Serialize)]
pub struct ParamRange {
    /// `ShellParams` field name (e.g. `"rib_ax_count"`). MUST match exactly.
    pub key: &'static str,
    /// Human-readable label for the UI slider.
    pub label: &'static str,
    pub min: f32,
    pub max: f32,
    pub step: f32,
    pub default: f32,
    /// Integer-valued: clamping rounds to the nearest integer; the UI shows no
    /// decimals.
    pub integer: bool,
}

/// The 19 user-facing shape parameters, in UI display order. This is the single
/// source of truth for every parameter's range.
///
/// Bounds are chosen to span the real diversity of **coiled** shells (Raup 1966
/// morphospace + malacology): augers/*Turritella* reach ~20 whorls, open coils
/// reach D≈0.95, spiny *Murex* and fine spiral cords push the ornament counts.
/// The degenerate high-W limpet/single-bivalve-valve case is intentionally out
/// of scope. `seg_theta`/`seg_phi` are absent — they are internal and
/// auto-derived from the ornament frequency, not user parameters.
pub const PARAM_RANGES: &[ParamRange] = &[
    // --- Layer 1: coiling geometry ---
    ParamRange { key: "w",            label: "Whorl expansion W",       min: 1.05, max: 8.0,    step: 0.01, default: 2.0,  integer: false },
    ParamRange { key: "d",            label: "Openness D",              min: 0.0,  max: 0.95,   step: 0.01, default: 0.15, integer: false },
    ParamRange { key: "t",            label: "Translation T",           min: 0.0,  max: 12.0,   step: 0.01, default: 1.5,  integer: false },
    ParamRange { key: "n",            label: "Whorls n",                min: 0.5,  max: 20.0,   step: 0.1,  default: 5.0,  integer: false },
    ParamRange { key: "aspect",       label: "Aperture aspect",         min: 0.3,  max: 4.0,    step: 0.01, default: 1.0,  integer: false },
    // --- Layer 2: ribs / cords / waves ---
    ParamRange { key: "rib_ax_count", label: "Axial ribs / waves",      min: 0.0,  max: 40.0,   step: 1.0,  default: 0.0,  integer: true  },
    ParamRange { key: "rib_ax_amp",   label: "Axial amplitude",         min: 0.0,  max: 0.6,    step: 0.01, default: 0.0,  integer: false },
    ParamRange { key: "rib_sp_count", label: "Spiral cords",            min: 0.0,  max: 60.0,   step: 1.0,  default: 0.0,  integer: true  },
    ParamRange { key: "rib_sp_amp",   label: "Spiral amplitude",        min: 0.0,  max: 0.6,    step: 0.01, default: 0.0,  integer: false },
    ParamRange { key: "rib_sharp",    label: "Profile (wave → ridge)",  min: 0.0,  max: 1.0,    step: 0.01, default: 0.0,  integer: false },
    // --- projections (nodules → spines) ---
    ParamRange { key: "proj_count",   label: "Projections / whorl",     min: 0.0,  max: 30.0,   step: 1.0,  default: 0.0,  integer: true  },
    ParamRange { key: "proj_rows",    label: "Rows around aperture",    min: 0.0,  max: 5.0,    step: 1.0,  default: 0.0,  integer: true  },
    ParamRange { key: "proj_pos",     label: "Row position (φ)",        min: 0.0,  max: 6.2832, step: 0.01, default: 0.0,  integer: false },
    ParamRange { key: "proj_size",    label: "Size",                    min: 0.0,  max: 1.2,    step: 0.01, default: 0.0,  integer: false },
    ParamRange { key: "proj_sharp",   label: "Sharpness (bead → needle)", min: 0.0, max: 1.0,   step: 0.01, default: 0.0,  integer: false },
    // --- varices ---
    ParamRange { key: "varix_count",  label: "Varices / whorl",         min: 0.0,  max: 6.0,    step: 1.0,  default: 0.0,  integer: true  },
    ParamRange { key: "varix_amp",    label: "Varix prominence",        min: 0.0,  max: 0.5,    step: 0.01, default: 0.0,  integer: false },
    // --- randomness ---
    ParamRange { key: "seed",         label: "Seed",                    min: 0.0,  max: 9999.0, step: 1.0,  default: 0.0,  integer: true  },
    ParamRange { key: "jitter",       label: "Jitter",                  min: 0.0,  max: 1.0,    step: 0.01, default: 0.0,  integer: false },
];

/// Layer-3 pigmentation parameters, exposed to the UI separately from the shape
/// table (they drive the reaction–diffusion engine, not the geometry). Same
/// `ParamRange` contract and single-source-of-truth role as [`PARAM_RANGES`];
/// `clamp_in_place` clamps these too. The palette/material (Layer 4) is applied
/// viewer-side and is intentionally not here.
pub const PIGMENT_RANGES: &[ParamRange] = &[
    ParamRange { key: "pig_regime",       label: "Pattern",      min: 0.0, max: 6.0, step: 1.0,  default: 0.0, integer: true  },
    ParamRange { key: "pig_scale",        label: "Feature scale", min: 0.0, max: 1.0, step: 0.01, default: 0.5, integer: false },
    ParamRange { key: "pig_contrast",     label: "Contrast",     min: 0.0, max: 1.0, step: 0.01, default: 0.5, integer: false },
    ParamRange { key: "pig_density",      label: "Density",      min: 0.0, max: 1.0, step: 0.01, default: 0.5, integer: false },
    ParamRange { key: "pig_angle",        label: "Obliqueness",  min: 0.0, max: 1.0, step: 0.01, default: 0.0, integer: false },
    ParamRange { key: "pig_irregularity", label: "Irregularity", min: 0.0, max: 1.0, step: 0.01, default: 0.0, integer: false },
];

impl ShellParams {
    /// Clamp every user-facing field to its `PARAM_RANGES` bound, rounding the
    /// integer-valued fields. `seg_theta`/`seg_phi` are left untouched (internal,
    /// auto-derived). After this, every shape field is guaranteed in range.
    pub fn clamp_in_place(&mut self) {
        fn fix(v: f32, r: &ParamRange) -> f32 {
            let c = v.clamp(r.min, r.max);
            if r.integer {
                c.round()
            } else {
                c
            }
        }
        // Panics only if a range table is missing a key — caught by the unit
        // tests `param_table_covers_every_field` / `pigment_table_is_wellformed`,
        // so it can never reach production.
        let g = |k| {
            PARAM_RANGES
                .iter()
                .chain(PIGMENT_RANGES.iter())
                .find(|r| r.key == k)
                .expect("missing range-table key")
        };
        self.w = fix(self.w, g("w"));
        self.d = fix(self.d, g("d"));
        self.t = fix(self.t, g("t"));
        self.n = fix(self.n, g("n"));
        self.aspect = fix(self.aspect, g("aspect"));
        self.rib_ax_count = fix(self.rib_ax_count, g("rib_ax_count"));
        self.rib_ax_amp = fix(self.rib_ax_amp, g("rib_ax_amp"));
        self.rib_sp_count = fix(self.rib_sp_count, g("rib_sp_count"));
        self.rib_sp_amp = fix(self.rib_sp_amp, g("rib_sp_amp"));
        self.rib_sharp = fix(self.rib_sharp, g("rib_sharp"));
        self.proj_count = fix(self.proj_count, g("proj_count"));
        self.proj_rows = fix(self.proj_rows, g("proj_rows"));
        self.proj_pos = fix(self.proj_pos, g("proj_pos"));
        self.proj_size = fix(self.proj_size, g("proj_size"));
        self.proj_sharp = fix(self.proj_sharp, g("proj_sharp"));
        self.varix_count = fix(self.varix_count, g("varix_count"));
        self.varix_amp = fix(self.varix_amp, g("varix_amp"));
        self.seed = fix(self.seed, g("seed"));
        self.jitter = fix(self.jitter, g("jitter"));
        self.pig_regime = fix(self.pig_regime, g("pig_regime"));
        self.pig_scale = fix(self.pig_scale, g("pig_scale"));
        self.pig_contrast = fix(self.pig_contrast, g("pig_contrast"));
        self.pig_density = fix(self.pig_density, g("pig_density"));
        self.pig_angle = fix(self.pig_angle, g("pig_angle"));
        self.pig_irregularity = fix(self.pig_irregularity, g("pig_irregularity"));
    }

    /// A clamped copy — see [`ShellParams::clamp_in_place`].
    pub fn clamped(&self) -> ShellParams {
        let mut p = self.clone();
        p.clamp_in_place();
        p
    }
}

/// A triangle mesh as flat buffers, ready to hand to a GPU / Three.js.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Mesh {
    /// xyz position triples.
    pub positions: Vec<f32>,
    /// xyz normal triples (per vertex, parallel to `positions`).
    pub normals: Vec<f32>,
    /// uv pairs (per vertex): u along the coil, v around the aperture.
    pub uvs: Vec<f32>,
    /// Triangle indices into the vertex arrays.
    pub indices: Vec<u32>,
    /// Layer-3 pigment field, row-major `pig_h` rows × `pig_w` columns, one byte
    /// per texel (0 = unpigmented base, 255 = full pigment). Produced by a 1-D
    /// reaction–diffusion line run along the aperture lip (φ → texture height /
    /// `v`) and stepped once per growth ring (θ → texture width / `u`) — the same
    /// growth sweep that builds the geometry, so it maps onto the mesh's existing
    /// UVs with no distortion (sample with `wrapT`/v = repeat for the closed lip,
    /// `wrapS`/u = clamp along the coil). Solid regime → a uniform field.
    pub pigment: Vec<u8>,
    /// Pigment texture width — samples along the coil (θ / `u`).
    pub pig_w: u32,
    /// Pigment texture height — samples around the aperture lip (φ / `v`).
    pub pig_h: u32,
}

/// Rib / wave profile in `[-1, 1]`. `sharp` morphs a smooth cosine **wave** (0)
/// into a narrow knife-edge **ridge** (1) by peaking a raised cosine.
#[inline]
fn ribbed(x: f32, sharp: f32) -> f32 {
    let c = 0.5 * (x.cos() + 1.0); // raised cosine, 0..1
    let p = 1.0 + sharp.clamp(0.0, 1.0) * 8.0; // exponent narrows the peak
    2.0 * c.powf(p) - 1.0
}

/// Positive periodic lobe in `[0, 1]`, peaking at multiples of 2π. `power`
/// narrows it: low = broad bump (nodule / varix), high = narrow spike (needle).
#[inline]
fn lobe(x: f32, power: f32) -> f32 {
    x.cos().max(0.0).powf(power)
}

// --- seeded value noise (pure function of the seed → reproducible randomness) ---

#[inline]
fn hash_u32(mut x: u32) -> u32 {
    x ^= x >> 16;
    x = x.wrapping_mul(0x7feb_352d);
    x ^= x >> 15;
    x = x.wrapping_mul(0x846c_a68b);
    x ^= x >> 16;
    x
}

/// Hash `(seed, i)` → f32 in `[0, 1)`.
#[inline]
fn rand01(seed: u32, i: i32) -> f32 {
    let h = hash_u32(seed ^ hash_u32(i as u32));
    (h >> 8) as f32 / ((1u32 << 24) as f32)
}

/// Hash `(seed, i)` → f32 in `[-1, 1)`.
#[inline]
fn rand_signed(seed: u32, i: i32) -> f32 {
    rand01(seed, i) * 2.0 - 1.0
}

/// Smooth 1-D value noise in `[-1, 1]` (lattice values, smoothstep-interpolated).
#[inline]
fn noise1(seed: u32, x: f32) -> f32 {
    let i = x.floor();
    let f = x - i;
    let ii = i as i32;
    let a = rand01(seed, ii);
    let b = rand01(seed, ii + 1);
    let u = f * f * (3.0 - 2.0 * f);
    (a + (b - a) * u) * 2.0 - 1.0
}

// ===========================================================================
// Layer 3 — pigmentation (reaction–diffusion at the growing lip)
// ===========================================================================
//
// Biology (Meinhardt, *The Algorithmic Beauty of Sea Shells*): shell pigment is
// secreted by the mantle edge at the growing aperture. Pigment cells sit along
// that edge (a closed loop = φ) and switch on/off based on their neighbours —
// a 1-D reaction–diffusion line. As the shell grows (θ advances) the line's
// state is frozen into the shell, so the 2-D surface pattern is the *space–time
// record* of the line: φ across, growth-time θ along. That is exactly the mesh
// sweep, so pigment and geometry share one growth process and the mesh's
// (u=θ, v=φ) UVs map the pattern with no distortion.
//
// The core is a Gray–Scott reaction–diffusion line (robust across regimes; its
// (F,K) sit in Pearson's pattern space). Different `PigRegime`s steer it: a
// drift term advects the pattern around the lip (oblique / chevron leans), and
// a commarginal growth-rhythm oscillation (a temporal band, biologically the
// periodic deposition along a growth line) supplies axial stripes and combines
// with the RD stripes for spots (×) and reticulation (max). Coefficients are
// empirically tuned approximations — tweak against the species harness.

/// Pigment grid resolution around the lip (φ), independent of the mesh's `cols`
/// so the pattern stays crisp on a cheap mesh.
const PIG_PHI: usize = 256;
/// Growth-time (θ) samples per whorl, bounded so long augers stay affordable.
const PIG_THETA_PER_WHORL: f32 = 200.0;
const PIG_THETA_MIN: usize = 64;
const PIG_THETA_MAX: usize = 3072;
/// RD steps to settle the line before recording the apex column.
const PIG_BURN_IN: usize = 400;
/// Decorrelates the pigment RNG from the geometry jitter salts.
const S_PIGMENT: u32 = 0x5F1C_3A2B;

/// Linear interpolation with a clamped parameter.
#[inline]
fn lerp(a: f32, b: f32, t: f32) -> f32 {
    a + (b - a) * t.clamp(0.0, 1.0)
}

/// Hermite smoothstep in `[0, 1]`.
#[inline]
fn smoothstep(e0: f32, e1: f32, x: f32) -> f32 {
    let t = ((x - e0) / (e1 - e0)).clamp(0.0, 1.0);
    t * t * (3.0 - 2.0 * t)
}

/// Pigment pattern families (the `pig_regime` index). Each selects a Gray–Scott
/// configuration / combination of the shared RD line; the continuous `pig_*`
/// knobs modulate within a family.
#[derive(Clone, Copy, PartialEq)]
enum PigRegime {
    Solid,
    SpiralBands,
    AxialStripes,
    ObliqueLines,
    Chevrons,
    Spots,
    Reticulated,
}

impl PigRegime {
    fn from_index(i: f32) -> Self {
        match i.round() as i32 {
            1 => Self::SpiralBands,
            2 => Self::AxialStripes,
            3 => Self::ObliqueLines,
            4 => Self::Chevrons,
            5 => Self::Spots,
            6 => Self::Reticulated,
            _ => Self::Solid,
        }
    }
}

/// One explicit-Euler Gray–Scott step on a periodic 1-D line, writing the next
/// state into `un`/`vn`. `drift` advects `v` around the lip (upwind) so the
/// pattern can travel. `u` ≈ substrate (1 = full), `v` ≈ activator → pigment.
#[allow(clippy::too_many_arguments)]
fn gs_step(u: &[f32], v: &[f32], un: &mut [f32], vn: &mut [f32], du: f32, dv: f32, f: f32, k: f32, drift: f32) {
    let n = u.len();
    for j in 0..n {
        let jm = if j == 0 { n - 1 } else { j - 1 };
        let jp = if j == n - 1 { 0 } else { j + 1 };
        let lap_u = u[jm] + u[jp] - 2.0 * u[j];
        let lap_v = v[jm] + v[jp] - 2.0 * v[j];
        let uvv = u[j] * v[j] * v[j];
        let du_dt = du * lap_u - uvv + f * (1.0 - u[j]);
        let dv_dt = dv * lap_v + uvv - (f + k) * v[j] - drift * (v[j] - v[jm]);
        // dt = 1 (the chosen diffusion/feed coefficients keep this stable).
        un[j] = (u[j] + du_dt).clamp(0.0, 1.5);
        vn[j] = (v[j] + dv_dt).clamp(0.0, 1.5);
    }
}

/// Generate the Layer-3 pigment field for `p`. Returns `(field, width=θ,
/// height=φ)`, row-major over φ. Deterministic from `p.seed`. The geometry is
/// untouched — this only reads the params that describe the pattern.
fn pigment_field(p: &ShellParams) -> (Vec<u8>, u32, u32) {
    let regime = PigRegime::from_index(p.pig_regime);
    let nx = ((p.n * PIG_THETA_PER_WHORL).round() as usize).clamp(PIG_THETA_MIN, PIG_THETA_MAX);
    let ny = PIG_PHI;
    let mut out = vec![0u8; nx * ny];

    // Solid → a uniform field; the base colour fills the whole shell.
    if regime == PigRegime::Solid {
        return (out, nx as u32, ny as u32);
    }

    let scale = p.pig_scale.clamp(0.0, 1.0);
    let contrast = p.pig_contrast.clamp(0.0, 1.0);
    let density = p.pig_density.clamp(0.0, 1.0);
    let angle = p.pig_angle.clamp(0.0, 1.0);
    let irreg = p.pig_irregularity.clamp(0.0, 1.0);
    let seed = (p.seed.max(0.0) as u32) ^ S_PIGMENT;

    // Contrast → smoothstep window around the mid-tone: crisp edge (high) vs.
    // soft gradient (low, which the viewer palette renders as accent mid-tones).
    let half = lerp(0.35, 0.02, contrast);
    let edge = |x: f32| smoothstep(0.5 - half, 0.5 + half, x);

    // Commarginal growth-rhythm oscillation: a band in growth-time (θ), uniform
    // around the lip. Used directly for axial stripes and as the transverse
    // factor for spots / reticulation.
    let bands_per_whorl = lerp(1.5, 10.0, density);
    let axial_at = |i: usize| -> f32 {
        let whorls = (i as f32 / nx as f32) * p.n;
        let mut ph = whorls * bands_per_whorl * (2.0 * PI);
        if irreg > 0.0 {
            ph += irreg * 1.5 * noise1(seed ^ 0x1111_2222, whorls * 3.0);
        }
        0.5 + 0.5 * ph.cos()
    };

    if regime == PigRegime::AxialStripes {
        for i in 0..nx {
            let b = (edge(axial_at(i)) * 255.0).round() as u8;
            for j in 0..ny {
                out[j * nx + i] = b;
            }
        }
        return (out, nx as u32, ny as u32);
    }

    // --- Gray–Scott line advanced over growth-time --------------------------
    // Feature scale sets the simulation's φ resolution: the GS stripe wavelength
    // is fixed (so the pattern is always reliable), so fewer sim cells spread
    // the same wavelength over fewer features around the lip (coarse), more
    // cells over more features (fine). The ny_sim line is resampled to the
    // PIG_PHI output rows, so the texture stays smooth either way.
    let (f, k) = (0.035, 0.060); // Pearson stripe/maze regime → periodic peaks
    let du = 0.16;
    let dv = 0.08;
    // Snap to a multiple of the seed spacing so nucleation wraps evenly around
    // the periodic lip (no seam where the last gap differs from the rest).
    const SEED_SPACING: usize = 16;
    let ny_sim = (((lerp(384.0, 48.0, scale) / SEED_SPACING as f32).round() as usize) * SEED_SPACING)
        .max(2 * SEED_SPACING); // large→fine, small→coarse
    let substeps = lerp(2.0, 12.0, density).round().max(1.0) as usize;
    // Obliqueness advects the pattern around the lip as the shell grows → a
    // diagonal lean, on *every* stripe regime (so the control always does
    // something). Oblique/chevron carry a baseline lean — that is their
    // character — and angle adds to it. Chevrons additionally mirror the drifted
    // field across the lip midline so the two leans meet in V-tents (below).
    // Keep the per-step drift gentle — it accumulates over the long coil into a
    // strong lean, and too large a per-step advection breaks the stripes into
    // dashes instead of leaning them.
    let drift_base = match regime {
        PigRegime::ObliqueLines => 0.08,
        PigRegime::Chevrons => 0.12,
        _ => 0.0,
    };
    let drift = drift_base + 0.06 * angle;

    let mut u = vec![1.0f32; ny_sim];
    let mut v = vec![0.0f32; ny_sim];
    // Nucleate at the constant ~intrinsic stripe spacing (≈ the GS wavelength at
    // this du/dv), so the stripes are stable (neither merge nor split) and the
    // feature count is ny_sim / spacing — i.e. driven by `scale` via ny_sim.
    // irregularity sprinkles extra seeds for natural variation.
    for j in (0..ny_sim).step_by(SEED_SPACING) {
        v[j] = 0.5;
        u[j] = 0.25;
    }
    if irreg > 0.0 {
        for j in 0..ny_sim {
            if rand01(seed, j as i32) < irreg * 0.15 {
                v[j] = 0.5;
                u[j] = 0.25;
            }
        }
    }

    let mut un = vec![0.0f32; ny_sim];
    let mut vn = vec![0.0f32; ny_sim];
    for _ in 0..PIG_BURN_IN {
        gs_step(&u, &v, &mut un, &mut vn, du, dv, f, k, 0.0);
        std::mem::swap(&mut u, &mut un);
        std::mem::swap(&mut v, &mut vn);
    }

    // Raw activator field on the sim grid; normalised after the sweep so the
    // contrast mapping is robust regardless of the regime's concentration range.
    let mut raw = vec![0.0f32; nx * ny_sim];
    for i in 0..nx {
        for _ in 0..substeps {
            gs_step(&u, &v, &mut un, &mut vn, du, dv, f, k, drift);
            std::mem::swap(&mut u, &mut un);
            std::mem::swap(&mut v, &mut vn);
        }
        if irreg > 0.0 && rand01(seed ^ 0xABCD, i as i32) < irreg * 0.05 {
            let j = (rand01(seed ^ 0x1234, i as i32) * ny_sim as f32) as usize % ny_sim;
            v[j] = 0.5;
            u[j] = 0.25;
        }
        for j in 0..ny_sim {
            raw[j * nx + i] = v[j];
        }
    }

    let (mut lo, mut hi) = (f32::INFINITY, f32::NEG_INFINITY);
    for &x in &raw {
        lo = lo.min(x);
        hi = hi.max(x);
    }
    let span = (hi - lo).max(1e-6);
    // Resample the ny_sim line onto the PIG_PHI (`ny`) output rows.
    for i in 0..nx {
        let ax = axial_at(i);
        for jo in 0..ny {
            let js = jo * ny_sim / ny;
            let gs = (raw[js * nx + i] - lo) / span;
            // Spots = RD stripes ∧ transverse rhythm (dots at intersections);
            // reticulated = RD stripes ∨ rhythm (net); chevrons = the drifted
            // diagonal ∨ its φ-mirror (the two leans meet in V-tents); others use
            // the RD field directly.
            let combined = match regime {
                PigRegime::Spots => gs * ax,
                PigRegime::Reticulated => gs.max(ax),
                PigRegime::Chevrons => {
                    let mirror = (raw[(ny_sim - 1 - js) * nx + i] - lo) / span;
                    gs.max(mirror)
                }
                _ => gs,
            };
            out[jo * nx + i] = (edge(combined) * 255.0).round().clamp(0.0, 255.0) as u8;
        }
    }
    (out, nx as u32, ny as u32)
}

/// Generate a shell surface by sweeping an elliptical aperture along a
/// logarithmic helico-spiral.
///
/// `theta` runs along the coil (0 .. 2π·n); `phi` runs around the aperture.
/// The aperture and its distance from the axis both scale by `g = W^(theta/2π)`,
/// which keeps the form self-similar (why shells are logarithmic spirals).
pub fn generate(p: &ShellParams) -> Mesh {
    // Single, total clamp: every shape field is now guaranteed within its
    // `PARAM_RANGES` bound, so the rest of the function (and the tessellation /
    // mesh math below) never sees an out-of-range value.
    let p = p.clamped();
    let p = &p;
    let n = p.n;
    let d = p.d;
    let aspect = p.aspect;
    let w = p.w;

    // Feature profile exponents — also drive how narrow each feature is.
    const VARIX_POWER: f32 = 3.0; // rounded raised ridges
    let rib_power = 1.0 + p.rib_sharp.clamp(0.0, 1.0) * 8.0; // matches `ribbed`
    let proj_power = 2.0 + p.proj_sharp.clamp(0.0, 1.0).powi(2) * 40.0; // matches `lobe` use
    let proj_active = p.proj_size.abs() > 1e-6 && p.proj_count > 0.5 && p.proj_rows > 0.5;

    // Auto-refine tessellation per direction from the *impacting* parameters:
    // a feature needs enough samples across each peak, and sharper peaks (higher
    // profile power) are narrower — so required resolution ≈ frequency · √power,
    // not a flat per-feature constant. This is why a sharp projection needs far
    // denser segments than a blunt one. Plain shells keep the cheap base res; a
    // global vertex budget bounds many-whorl × sharp combos.
    const SPC: f32 = 16.0; // samples per feature-cycle at power 1
    const MAX_THETA: u32 = 768;
    const MAX_PHI: u32 = 384;
    const VERT_BUDGET: f32 = 800_000.0;
    let spc = |power: f32| SPC * power.sqrt();

    let mut theta_need = 0.0f32; // features periodic along the coil
    let mut phi_need = 0.0f32; // features periodic around the aperture
    if p.rib_ax_amp.abs() > 1e-6 {
        theta_need = theta_need.max(p.rib_ax_count * spc(rib_power));
    }
    if p.rib_sp_amp.abs() > 1e-6 {
        phi_need = phi_need.max(p.rib_sp_count * spc(rib_power));
    }
    if p.varix_amp.abs() > 1e-6 {
        theta_need = theta_need.max(p.varix_count * spc(VARIX_POWER));
    }
    if proj_active {
        theta_need = theta_need.max(p.proj_count * spc(proj_power));
        phi_need = phi_need.max(p.proj_rows.max(1.0) * spc(proj_power));
    }

    let base_theta = p.seg_theta.max(3);
    let base_phi = p.seg_phi.max(3);
    let mut seg_theta = (base_theta as f32).max(theta_need).ceil().min(MAX_THETA as f32) as u32;
    let mut seg_phi = (base_phi as f32).max(phi_need).ceil().min(MAX_PHI as f32) as u32;
    // Scale both down together if the total vertex count would blow the budget.
    let est = seg_theta as f32 * n * seg_phi as f32;
    if est > VERT_BUDGET {
        let s = (VERT_BUDGET / est).sqrt();
        seg_theta = ((seg_theta as f32 * s) as u32).max(base_theta);
        seg_phi = ((seg_phi as f32 * s) as u32).max(base_phi);
    }
    let cols = seg_phi as usize;

    let total_theta = n * 2.0 * PI;
    let k = w.ln() / (2.0 * PI); // growth rate: g = exp(k·theta) grows by W each turn

    // Total segments along the coil (segments-per-revolution × revolutions).
    let theta_steps = ((seg_theta as f32) * n).ceil().max(1.0) as usize;
    let theta_verts = theta_steps + 1;

    let mut positions = Vec::with_capacity(theta_verts * cols * 3);
    let mut normals = vec![0.0f32; theta_verts * cols * 3];
    let mut uvs = Vec::with_capacity(theta_verts * cols * 2);

    let two_pi = 2.0 * PI;
    let sharp = p.rib_sharp;

    // --- seeded randomness setup (jitter = 0 → exact uniform output) ---
    let jittered = p.jitter > 1e-6;
    let jit = p.jitter.clamp(0.0, 1.0);
    let seed = p.seed.max(0.0) as u32;
    // Distinct salts so the different effects are decorrelated. Each θ-periodic
    // feature gets its own *position* salt (irregular spacing) and *amplitude*
    // salt (irregular height).
    const S_AXPOS: u32 = 0x9E37_79B1; // rib axial θ-phase (spacing)
    const S_VXPOS: u32 = 0x85EB_CA77; // varix θ-phase (spacing)
    const S_PRPOS: u32 = 0xC2B2_AE3D; // projection θ-phase (spacing)
    const S_AXAMP: u32 = 0x27D4_EB2F;
    const S_VXAMP: u32 = 0x1656_67B1;
    const S_PRAMP: u32 = 0xD3A2_646C;
    const S_SPAMP: u32 = 0xFD70_46C5;
    const S_PHIWARP: u32 = 0x7F4A_7C15;
    const S_COIL: u32 = 0xB55A_4F09;

    // Position jitter is applied in *argument space* (`count·θ + phase`), so a
    // fixed phase amplitude shifts every feature by the same fraction of its own
    // spacing regardless of count — coarse varices and fine ribs alike get
    // irregular *spacing*, not just height. `PH_POS / 2π ≈ 0.24` ⇒ ±24 % of a
    // feature's gap at jitter 1. The amplitude/frequency are bounded so
    // `count·θ + phase` stays monotonic (no mesh folds) down to one feature per
    // whorl: worst-case dphase/dθ ≈ jit·PH_POS·3·freq/2π < 1 ≤ count.
    const PH_POS: f32 = 1.5;

    for i in 0..theta_verts {
        let theta = total_theta * (i as f32) / (theta_steps as f32);
        let g = (k * theta).exp();
        let ap_r = aspect * g; // aperture radial semi-axis
        let ap_z = g; // aperture axial semi-axis
        let ct = theta.cos();
        let st = theta.sin();

        // Per-θ seeded jitter: an independent θ-phase per feature (so spacing
        // goes irregular and features drift across whorls instead of locking to
        // the same angle), per-instance amplitude wobble, a φ-shift (cords
        // meander), and a subtle coil radius wobble.
        let mut radius_wob = 1.0;
        let mut ax_ampj = 1.0;
        let mut varix_ampj = 1.0;
        let mut proj_ampj = 1.0;
        let mut phi_shift = 0.0;
        let (mut ax_ph, mut varix_ph, mut proj_ph) = (0.0f32, 0.0f32, 0.0f32);
        if jittered {
            let whorl = theta / two_pi;
            // Smooth, bounded θ-phase (argument-space) → irregular feature spacing.
            let phase = |salt: u32, freq: f32| jit * PH_POS * noise1(seed ^ salt, whorl * freq);
            ax_ph = phase(S_AXPOS, 1.0);
            varix_ph = phase(S_VXPOS, 0.85);
            proj_ph = phase(S_PRPOS, 0.95);
            radius_wob = 1.0 + jit * 0.04 * noise1(seed ^ S_COIL, whorl * 1.1 + 11.0);
            ax_ampj = 1.0 + jit * 0.5 * rand_signed(seed ^ S_AXAMP, (p.rib_ax_count * whorl).round() as i32);
            varix_ampj = 1.0 + jit * 0.7 * rand_signed(seed ^ S_VXAMP, (p.varix_count * whorl).round() as i32);
            proj_ampj = 1.0 + jit * 0.6 * rand_signed(seed ^ S_PRAMP, (p.proj_count * whorl).round() as i32);
            phi_shift = jit * 0.12 * noise1(seed ^ S_PHIWARP, theta * 0.4);
        }

        let radius = (ap_r / (1.0 - d)) * radius_wob; // axis → centre, with coil wobble
        let cz = p.t * radius; // centre height: ∝ radius gives the conical spire

        // θ-only ornament terms (per-feature phase → irregular spacing, and
        // features don't lock to the same angle every whorl).
        let axial = p.rib_ax_amp * ax_ampj * ribbed(p.rib_ax_count * theta + ax_ph, sharp);
        let varix = p.varix_amp * varix_ampj * lobe(p.varix_count * theta + varix_ph, VARIX_POWER);
        let proj_theta = lobe(p.proj_count * theta + proj_ph, proj_power);

        let u = i as f32 / theta_steps as f32; // 0..1 along the coil

        for col in 0..cols {
            let phi = two_pi * (col as f32) / (cols as f32);
            let phi_o = phi + phi_shift; // warped φ for ornament placement
            // Spiral cords: continuous along the coil → longitudinal cords.
            let cord_ampj = if jittered {
                1.0 + jit * 0.45 * rand_signed(seed ^ S_SPAMP, (p.rib_sp_count * phi / two_pi).round() as i32)
            } else {
                1.0
            };
            let spiral = p.rib_sp_amp * cord_ampj * ribbed(p.rib_sp_count * phi_o, sharp);
            // Projections: blunt beads (rows≥2, low sharp) → needle spines
            // (rows=1, high sharp), localised on a θ×φ grid offset by proj_pos.
            let proj = if proj_active {
                p.proj_size * proj_ampj * proj_theta * lobe(p.proj_rows * (phi_o - p.proj_pos), proj_power)
            } else {
                0.0
            };

            // Radial displacement along the aperture's outward direction, scaled
            // by g so ornament stays proportional along the whole shell.
            let disp = g * (axial + spiral + varix + proj);
            let rr = radius + (ap_r + disp) * phi.cos();
            positions.push(rr * ct); // x
            positions.push(rr * st); // y
            positions.push(cz + (ap_z + disp) * phi.sin()); // z
            uvs.push(u);
            uvs.push(col as f32 / cols as f32); // v around the aperture
        }
    }

    // Build quads between adjacent rings; phi wraps (closed tube), so j+1 is mod cols.
    let mut indices = Vec::with_capacity(theta_steps * cols * 6);
    let vid = |i: usize, j: usize| -> u32 { (i * cols + (j % cols)) as u32 };
    for i in 0..theta_steps {
        for j in 0..cols {
            let a = vid(i, j);
            let b = vid(i + 1, j);
            let c = vid(i + 1, j + 1);
            let e = vid(i, j + 1);
            indices.extend_from_slice(&[a, b, c, a, c, e]);
        }
    }

    // Smooth normals: accumulate face normals onto vertices, then normalise.
    for tri in indices.chunks_exact(3) {
        let (ia, ib, ic) = (tri[0] as usize, tri[1] as usize, tri[2] as usize);
        let pa = [positions[ia * 3], positions[ia * 3 + 1], positions[ia * 3 + 2]];
        let pb = [positions[ib * 3], positions[ib * 3 + 1], positions[ib * 3 + 2]];
        let pc = [positions[ic * 3], positions[ic * 3 + 1], positions[ic * 3 + 2]];
        let u = [pb[0] - pa[0], pb[1] - pa[1], pb[2] - pa[2]];
        let v = [pc[0] - pa[0], pc[1] - pa[1], pc[2] - pa[2]];
        let nrm = [
            u[1] * v[2] - u[2] * v[1],
            u[2] * v[0] - u[0] * v[2],
            u[0] * v[1] - u[1] * v[0],
        ];
        for &idx in &[ia, ib, ic] {
            normals[idx * 3] += nrm[0];
            normals[idx * 3 + 1] += nrm[1];
            normals[idx * 3 + 2] += nrm[2];
        }
    }
    for nrm in normals.chunks_exact_mut(3) {
        let len = (nrm[0] * nrm[0] + nrm[1] * nrm[1] + nrm[2] * nrm[2]).sqrt();
        if len > 1e-8 {
            nrm[0] /= len;
            nrm[1] /= len;
            nrm[2] /= len;
        }
    }

    // Normalise to a unit sphere centred at the origin. Raw coords span a huge
    // range (g = e^(kθ) can reach thousands), which wrecks downstream float
    // precision (BVH / ray tracing). Translate + uniform scale leave the
    // already-unit normals unchanged.
    let vcount = (positions.len() / 3).max(1) as f32;
    let (mut cx, mut cy, mut cz) = (0.0f32, 0.0f32, 0.0f32);
    for v in positions.chunks_exact(3) {
        cx += v[0];
        cy += v[1];
        cz += v[2];
    }
    cx /= vcount;
    cy /= vcount;
    cz /= vcount;
    let mut max_r2 = 0.0f32;
    for v in positions.chunks_exact(3) {
        let (dx, dy, dz) = (v[0] - cx, v[1] - cy, v[2] - cz);
        max_r2 = max_r2.max(dx * dx + dy * dy + dz * dz);
    }
    let scale = 1.0 / max_r2.sqrt().max(1e-6);
    for v in positions.chunks_exact_mut(3) {
        v[0] = (v[0] - cx) * scale;
        v[1] = (v[1] - cy) * scale;
        v[2] = (v[2] - cz) * scale;
    }

    // --- Orient for display ---------------------------------------------------
    // The coil is built around +Z with the apex (smallest whorl) at the low-z end
    // and the body whorl / aperture at the high-z end. For viewing we want a
    // canonical pose: the coil axis vertical with the cone pointing *down*, and
    // the body whorl turned to face the camera (+Z). Two rotations about the now-
    // centred origin do it — rotations preserve the unit normalisation above and
    // keep the (already unit) normals valid.
    //
    // 1) Spin about the coil axis (Z) so the body whorl's azimuth points to
    //    (0,-1); 2) tip upright with Rx(-90°): (x,y,z) -> (x, z, -y), which sends
    //    +Z (coil axis) -> +Y (up), the low-z apex -> -Y (bottom), and the body
    //    whorl -> +Z (front).
    let last = (theta_verts - 1) * cols;
    let (mut ax, mut ay) = (0.0f32, 0.0f32);
    for c in 0..cols {
        let b = (last + c) * 3;
        ax += positions[b];
        ay += positions[b + 1];
    }
    ax /= cols as f32;
    ay /= cols as f32;
    let rho = -0.5 * PI - ay.atan2(ax);
    let (sr, cr) = rho.sin_cos();
    let orient = |p: &mut [f32]| {
        let (x, y, z) = (p[0], p[1], p[2]);
        p[0] = x * cr - y * sr; // x' = Rz(rho)·x
        p[1] = z; //               y' = z   (coil axis -> up)
        p[2] = -(x * sr + y * cr); // z' = -y'
    };
    for v in positions.chunks_exact_mut(3) {
        orient(v);
    }
    for nrm in normals.chunks_exact_mut(3) {
        orient(nrm);
    }

    // Layer 3: pigment laid down by the same growth process (shares `seed` and
    // the coil extent); independent grid resolution, mapped via the UVs above.
    let (pigment, pig_w, pig_h) = pigment_field(p);

    Mesh {
        positions,
        normals,
        uvs,
        indices,
        pigment,
        pig_w,
        pig_h,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn param_table_covers_every_field() {
        // 19 user-facing shape params, unique keys, defaults inside their range.
        assert_eq!(PARAM_RANGES.len(), 19);
        let mut keys: Vec<_> = PARAM_RANGES.iter().map(|r| r.key).collect();
        keys.sort_unstable();
        keys.dedup();
        assert_eq!(keys.len(), 19, "duplicate or missing PARAM_RANGES key");
        for r in PARAM_RANGES {
            assert!(r.min <= r.max, "{}: min > max", r.key);
            assert!(r.step > 0.0, "{}: non-positive step", r.key);
            assert!(
                r.default >= r.min && r.default <= r.max,
                "{}: default out of range",
                r.key
            );
            if r.integer {
                assert_eq!(r.default.fract(), 0.0, "{}: integer default not whole", r.key);
            }
        }
        // The `Default` impl must agree with the table's defaults.
        let d = ShellParams::default();
        let by = |k| PARAM_RANGES.iter().find(|r| r.key == k).unwrap().default;
        assert_eq!(d.w, by("w"));
        assert_eq!(d.d, by("d"));
        assert_eq!(d.t, by("t"));
        assert_eq!(d.n, by("n"));
        assert_eq!(d.aspect, by("aspect"));
    }

    #[test]
    fn clamp_pins_out_of_range_and_rounds_integers() {
        let p = ShellParams {
            w: 100.0,        // above max 8.0
            d: 5.0,          // above max 0.95
            t: -3.0,         // below min 0.0
            n: 999.0,        // above max 20.0
            aspect: 0.01,    // below min 0.3
            proj_count: -7.0, // below min, integer
            varix_count: 4.7, // integer rounding
            jitter: 2.0,     // above max 1.0
            ..ShellParams::default()
        }
        .clamped();
        assert_eq!(p.w, 8.0);
        assert_eq!(p.d, 0.95);
        assert_eq!(p.t, 0.0);
        assert_eq!(p.n, 20.0);
        assert_eq!(p.aspect, 0.3);
        assert_eq!(p.proj_count, 0.0);
        assert_eq!(p.varix_count, 5.0); // 4.7 rounds to nearest int
        assert_eq!(p.jitter, 1.0);
        // every field lands within its declared range
        for r in PARAM_RANGES {
            let v = match r.key {
                "w" => p.w, "d" => p.d, "t" => p.t, "n" => p.n, "aspect" => p.aspect,
                "rib_ax_count" => p.rib_ax_count, "rib_ax_amp" => p.rib_ax_amp,
                "rib_sp_count" => p.rib_sp_count, "rib_sp_amp" => p.rib_sp_amp,
                "rib_sharp" => p.rib_sharp, "proj_count" => p.proj_count,
                "proj_rows" => p.proj_rows, "proj_pos" => p.proj_pos,
                "proj_size" => p.proj_size, "proj_sharp" => p.proj_sharp,
                "varix_count" => p.varix_count, "varix_amp" => p.varix_amp,
                "seed" => p.seed, "jitter" => p.jitter,
                other => panic!("untested key {other}"),
            };
            assert!(v >= r.min && v <= r.max, "{} out of range after clamp: {v}", r.key);
        }
    }

    #[test]
    fn generate_is_safe_for_wild_input() {
        // Garbage in → a finite, well-formed mesh out (clamp guards the math).
        let wild = ShellParams {
            w: 1e6,
            d: 12.0,
            n: 5000.0,
            proj_count: 1e4,
            rib_sp_count: 1e4,
            varix_count: -50.0,
            ..ShellParams::default()
        };
        let m = generate(&wild);
        assert!(!m.positions.is_empty());
        assert!(m.positions.iter().all(|x| x.is_finite()));
    }

    #[test]
    fn mesh_is_wellformed() {
        let m = generate(&ShellParams::default());
        assert!(!m.positions.is_empty());
        assert_eq!(m.positions.len() % 3, 0);
        assert_eq!(m.normals.len(), m.positions.len());
        assert_eq!(m.uvs.len(), m.positions.len() / 3 * 2);
        assert_eq!(m.indices.len() % 3, 0);
        assert!(m.positions.iter().all(|x| x.is_finite()));
        let vcount = (m.positions.len() / 3) as u32;
        assert!(m.indices.iter().all(|&i| i < vcount), "index out of range");
    }

    #[test]
    fn normals_are_unit_length() {
        let m = generate(&ShellParams::default());
        for nrm in m.normals.chunks_exact(3) {
            let len = (nrm[0] * nrm[0] + nrm[1] * nrm[1] + nrm[2] * nrm[2]).sqrt();
            assert!((len - 1.0).abs() < 1e-3, "normal not unit: {len}");
        }
    }

    #[test]
    fn ribs_perturb_the_surface_but_stay_finite() {
        // Pin resolution at the caps on both so auto-refinement clamps equally,
        // keeping topology identical for an element-wise comparison.
        let base = ShellParams {
            seg_phi: 384,
            seg_theta: 768,
            ..ShellParams::default()
        };
        let smooth = generate(&base);
        let ribbed = generate(&ShellParams {
            rib_ax_count: 14.0,
            rib_ax_amp: 0.25,
            rib_sp_count: 10.0,
            rib_sp_amp: 0.15,
            rib_sharp: 0.5,
            ..base.clone()
        });
        assert_eq!(smooth.positions.len(), ribbed.positions.len());
        let moved = smooth
            .positions
            .iter()
            .zip(&ribbed.positions)
            .any(|(a, b)| (a - b).abs() > 1e-4);
        assert!(moved, "ornamentation should change vertex positions");
        assert!(ribbed.positions.iter().all(|x| x.is_finite()));
    }

    #[test]
    fn projections_and_varices_each_perturb_and_stay_finite() {
        let base = ShellParams {
            seg_phi: 384,
            seg_theta: 768,
            ..ShellParams::default()
        };
        let smooth = generate(&base);
        let variants = [
            // single-row needle spine
            ShellParams { proj_count: 8.0, proj_rows: 1.0, proj_pos: 1.1, proj_size: 0.8, proj_sharp: 0.75, ..base.clone() },
            // multi-row blunt nodules
            ShellParams { proj_count: 12.0, proj_rows: 2.0, proj_size: 0.12, proj_sharp: 0.15, ..base.clone() },
            ShellParams { varix_count: 3.0, varix_amp: 0.3, ..base.clone() },
        ];
        for (k, v) in variants.iter().enumerate() {
            let m = generate(v);
            assert_eq!(m.positions.len(), smooth.positions.len(), "variant {k} topology");
            let moved = smooth
                .positions
                .iter()
                .zip(&m.positions)
                .any(|(a, b)| (a - b).abs() > 1e-4);
            assert!(moved, "variant {k} should change the surface");
            assert!(m.positions.iter().all(|x| x.is_finite()), "variant {k} finite");
        }
    }

    #[test]
    fn jitter_zero_is_identical_regardless_of_seed() {
        let a = generate(&ShellParams::default());
        let b = generate(&ShellParams { seed: 9999.0, jitter: 0.0, ..ShellParams::default() });
        assert_eq!(a.positions, b.positions, "jitter=0 must ignore the seed exactly");
    }

    #[test]
    fn jitter_is_deterministic_and_seed_dependent() {
        let p1 = ShellParams {
            varix_count: 3.0,
            varix_amp: 0.3,
            jitter: 0.6,
            seed: 1.0,
            ..ShellParams::default()
        };
        let a = generate(&p1);
        let a2 = generate(&p1);
        let b = generate(&ShellParams { seed: 2.0, ..p1.clone() });
        let uniform = generate(&ShellParams { jitter: 0.0, ..p1.clone() });

        assert_eq!(a.positions, a2.positions, "same seed+params must reproduce exactly");
        assert_eq!(a.positions.len(), b.positions.len());
        assert!(
            a.positions.iter().zip(&b.positions).any(|(x, y)| (x - y).abs() > 1e-5),
            "different seeds should produce different shapes"
        );
        assert!(
            a.positions.iter().zip(&uniform.positions).any(|(x, y)| (x - y).abs() > 1e-5),
            "jitter should perturb the surface vs the uniform shape"
        );
    }

    #[test]
    fn seed_visibly_changes_spacing_not_just_height() {
        // Regression: at jitter=1 two seeds must differ *substantially* (irregular
        // spacing, not a cosmetic global rotation). Measured ~0.08 max displacement
        // with ~89% of vertices moving; assert well below that so it can't silently
        // regress to the old amplitude-only level. Topology is seed-independent, so
        // the vertex arrays line up element-wise.
        let base = ShellParams { varix_count: 4.0, varix_amp: 0.3, jitter: 1.0, ..ShellParams::default() };
        let a = generate(&ShellParams { seed: 1.0, ..base.clone() });
        let b = generate(&ShellParams { seed: 2.0, ..base.clone() });
        assert_eq!(a.positions.len(), b.positions.len(), "seed must not change topology");
        let n = a.positions.len() / 3;
        let disp = |i: usize| -> f32 {
            ((a.positions[i * 3] - b.positions[i * 3]).powi(2)
                + (a.positions[i * 3 + 1] - b.positions[i * 3 + 1]).powi(2)
                + (a.positions[i * 3 + 2] - b.positions[i * 3 + 2]).powi(2))
            .sqrt()
        };
        let max_disp = (0..n).map(disp).fold(0.0f32, f32::max);
        let moved = (0..n).filter(|&i| disp(i) > 0.01).count();
        assert!(max_disp > 0.03, "seeds barely differ (max disp {max_disp}) — jitter too weak");
        assert!(
            moved * 100 / n >= 40,
            "only {}% of vertices moved between seeds — spacing not randomized",
            moved * 100 / n
        );
        assert!(b.positions.iter().all(|x| x.is_finite()));
    }

    #[test]
    fn low_count_varices_do_not_fold_under_max_jitter() {
        // The argument-space phase bound (PH_POS) must keep `count·θ + phase`
        // monotonic even at one feature per whorl, so the swept tube never folds
        // back on itself (which would make a self-intersecting, NaN-free but
        // broken mesh). Smoke test the tightest case stays finite and bounded.
        for &count in &[1.0, 2.0, 3.0] {
            let m = generate(&ShellParams {
                varix_count: count,
                varix_amp: 0.5,
                jitter: 1.0,
                seed: 7.0,
                ..ShellParams::default()
            });
            assert!(m.positions.iter().all(|x| x.is_finite() && x.abs() <= 1.001), "count {count} unbounded/NaN");
        }
    }

    #[test]
    fn sharper_projections_get_denser_tessellation() {
        // Same count/size; only sharpness differs. The needle is narrower, so it
        // must auto-refine to a denser mesh than the blunt bead.
        let common = ShellParams {
            proj_count: 8.0,
            proj_rows: 1.0,
            proj_size: 0.4,
            ..ShellParams::default()
        };
        let blunt = generate(&ShellParams { proj_sharp: 0.1, ..common.clone() });
        let needle = generate(&ShellParams { proj_sharp: 1.0, ..common.clone() });
        assert!(
            needle.positions.len() > blunt.positions.len(),
            "a sharp needle should refine denser than a blunt bead ({} vs {})",
            needle.positions.len(),
            blunt.positions.len()
        );
    }

    #[test]
    fn tessellation_refines_for_high_frequency_cords() {
        let plain = generate(&ShellParams { seg_phi: 48, ..ShellParams::default() });
        let cords = generate(&ShellParams {
            seg_phi: 48,
            rib_sp_count: 16.0,
            rib_sp_amp: 0.1,
            ..ShellParams::default()
        });
        // Same θ resolution, but cords force a finer φ tessellation (16·12 > 48).
        assert!(
            cords.positions.len() > plain.positions.len(),
            "high-frequency cords should auto-refine the cross-section mesh"
        );
    }

    #[test]
    fn smooth_wave_is_symmetric_ridge_is_peaked() {
        // sharp=0 → mean ~0 (symmetric swell in/out); sharp=1 → mean <0 (narrow ridges).
        let n = 2000;
        let mean = |sharp: f32| {
            (0..n)
                .map(|i| ribbed(i as f32 / n as f32 * 2.0 * PI, sharp))
                .sum::<f32>()
                / n as f32
        };
        assert!(mean(0.0).abs() < 0.02, "smooth wave should be ~symmetric");
        assert!(mean(1.0) < -0.3, "sharp ridges should sit below baseline");
    }

    #[test]
    fn planispiral_centres_lie_in_a_plane() {
        // T = 0 → centre height is 0; the coil is flat. After the display
        // orientation the coil axis is the world Y, so a planispiral stays flat in
        // Y: max |y| is bounded by the largest aperture half-height (the only
        // out-of-plane extent), times the unit-normalisation scale (≤ 1).
        let p = ShellParams {
            t: 0.0,
            ..ShellParams::default()
        };
        let m = generate(&p);
        let g_max = p.w.powf(p.n);
        let max_y = m.positions.iter().skip(1).step_by(3).fold(0.0f32, |a, &y| a.max(y.abs()));
        assert!(max_y <= g_max * 1.01, "planispiral too tall: {max_y} vs {g_max}");
    }

    // --- Layer 3: pigmentation -------------------------------------------------

    #[test]
    fn pigment_table_is_wellformed() {
        let len = PIGMENT_RANGES.len();
        let mut keys: Vec<_> = PIGMENT_RANGES.iter().map(|r| r.key).collect();
        keys.sort_unstable();
        keys.dedup();
        assert_eq!(keys.len(), len, "duplicate or missing PIGMENT_RANGES key");
        for r in PIGMENT_RANGES {
            assert!(r.min <= r.max, "{}: min > max", r.key);
            assert!(r.step > 0.0, "{}: non-positive step", r.key);
            assert!(r.default >= r.min && r.default <= r.max, "{}: default out of range", r.key);
        }
        // Defaults must agree with the `Default` impl (single source of truth).
        let d = ShellParams::default();
        let by = |k| PIGMENT_RANGES.iter().find(|r| r.key == k).unwrap().default;
        assert_eq!(d.pig_regime, by("pig_regime"));
        assert_eq!(d.pig_scale, by("pig_scale"));
        assert_eq!(d.pig_contrast, by("pig_contrast"));
        assert_eq!(d.pig_density, by("pig_density"));
        assert_eq!(d.pig_angle, by("pig_angle"));
        assert_eq!(d.pig_irregularity, by("pig_irregularity"));
    }

    #[test]
    fn pigment_field_is_well_formed_and_solid_is_uniform() {
        let m = generate(&ShellParams { pig_regime: 0.0, ..ShellParams::default() });
        assert!(m.pig_w > 0 && m.pig_h > 0);
        assert_eq!(m.pigment.len(), (m.pig_w * m.pig_h) as usize);
        assert!(m.pigment.iter().all(|&b| b == m.pigment[0]), "solid regime must be uniform");
    }

    #[test]
    fn patterned_regimes_are_nonuniform_and_deterministic() {
        for regime in 1..=6 {
            let p = ShellParams {
                pig_regime: regime as f32,
                pig_irregularity: 0.3,
                seed: 3.0,
                ..ShellParams::default()
            };
            let a = generate(&p);
            let b = generate(&p);
            assert_eq!(a.pigment, b.pigment, "regime {regime} not reproducible");
            let first = a.pigment[0];
            assert!(
                a.pigment.iter().any(|&x| x != first),
                "regime {regime} produced no pattern"
            );
        }
    }

    #[test]
    fn pigment_is_periodic_around_the_lip() {
        // φ wraps (closed lip): the first and last rows are adjacent cells, so on
        // average they must be continuous — no hard seam where the texture wraps.
        let m = generate(&ShellParams { pig_regime: 1.0, ..ShellParams::default() });
        let (w, h) = (m.pig_w as usize, m.pig_h as usize);
        let mut diff = 0u32;
        for i in 0..w {
            let top = m.pigment[i] as i32;
            let bot = m.pigment[(h - 1) * w + i] as i32;
            diff += (top - bot).unsigned_abs();
        }
        let avg = diff as f32 / w as f32;
        assert!(avg < 90.0, "φ seam discontinuity too large: {avg}");
    }

    #[test]
    fn pigment_params_do_not_change_geometry() {
        // Pigmentation is a second output of the growth sweep; it must never move
        // a vertex. (Shape params still drive both, but pig_* are pattern-only.)
        let a = generate(&ShellParams::default());
        let b = generate(&ShellParams {
            pig_regime: 4.0,
            pig_scale: 0.8,
            pig_density: 0.9,
            pig_angle: 0.7,
            pig_irregularity: 0.5,
            seed: 12.0,
            ..ShellParams::default()
        });
        assert_eq!(a.positions, b.positions, "pigment params must not affect geometry");
    }
}
