//! The user-facing parameter model and its single source of truth.
//!
//! [`ShellParams`] is the full input to [`crate::generate`]; [`PARAM_RANGES`] and
//! [`PIGMENT_RANGES`] are the *only* place each parameter's `min`/`max`/`step`/
//! `default`/`integer` is defined, and [`ShellParams::clamp_in_place`] pins every
//! input to those bounds before any mesh math runs.

use serde::{Deserialize, Serialize};
use std::f32::consts::TAU;

/// Layer-1 coiling parameters (Raup W/D/T + practical extras).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ShellParams {
    /// Whorl expansion rate per revolution (> 1). Snails ~1.1–3, Nautilus ~3.
    pub w: f32,
    /// Openness: 0 = whorls touch the axis (tight), → 1 = open coil / wide umbilicus.
    pub d: f32,
    /// Translation rate along the axis. 0 = planispiral (flat), higher = tall spire.
    pub t: f32,
    /// Number of whorls (revolutions).
    pub n: f32,
    /// Aperture aspect ratio (radial semi-axis / axial semi-axis). 1 = circular tube.
    #[serde(default = "default_aspect")]
    pub aspect: f32,

    // --- Layer 2: rib / wave ornamentation (see parameters.md) ---
    /// Axial ribs/waves: number across the whorl, per revolution.
    #[serde(default)]
    pub rib_ax_count: f32,
    /// Axial amplitude as a fraction of tube radius. High = structural wave.
    #[serde(default)]
    pub rib_ax_amp: f32,
    /// Spiral cords: number around the aperture cross-section.
    #[serde(default)]
    pub rib_sp_count: f32,
    /// Spiral amplitude as a fraction of tube radius.
    #[serde(default)]
    pub rib_sp_amp: f32,
    /// Profile: 0 = smooth sine wave, 1 = sharp knife-edge ridge.
    #[serde(default)]
    pub rib_sharp: f32,

    // --- projections: the nodule → spine continuum ---
    /// Projections per whorl (count along the coil). 0 = none.
    #[serde(default)]
    pub proj_count: f32,
    /// Rows of projections around the aperture. 1 = single row (spine-like),
    /// ≥2 = evenly spaced rows (nodulose).
    #[serde(default)]
    pub proj_rows: f32,
    /// Position of the first row around the aperture, radians (0..2π).
    #[serde(default)]
    pub proj_pos: f32,
    /// Projection size (height/length) as a fraction of tube radius.
    #[serde(default)]
    pub proj_size: f32,
    /// Sharpness: 0 = rounded blunt bead (nodule), 1 = narrow needle (spine).
    #[serde(default)]
    pub proj_sharp: f32,

    // --- varices ---
    /// Varices (prominent transverse ridges) per whorl. 0 = none.
    #[serde(default)]
    pub varix_count: f32,
    /// Varix prominence as a fraction of tube radius.
    #[serde(default)]
    pub varix_amp: f32,

    // --- randomness (seeded → reproducible) ---
    /// Random seed (integer-valued). Same seed + params → identical shape.
    #[serde(default)]
    pub seed: f32,
    /// Randomness amount, 0..1. 0 = perfectly uniform (seed has no effect).
    #[serde(default)]
    pub jitter: f32,

    // --- Layer 3: pigmentation (reaction–diffusion at the growing lip) ---
    // The shell's colour pattern is laid down by the mantle edge at the growing
    // aperture, so it is generated by the *same* growth sweep as the geometry: a
    // 1-D reaction–diffusion line runs around the lip (φ) and is stepped once per
    // growth ring (θ). See `pigment_field`.
    /// Pattern regime (integer index into `PIGMENT_RANGES` / `PigRegime`):
    /// 0=solid, 1=spiral bands, 2=axial stripes, 3=oblique lines,
    /// 4=chevrons/tented, 5=spots, 6=reticulated. Selects the RD configuration.
    #[serde(default)]
    pub pig_regime: f32,
    /// Feature scale: small = fine/many features, large = coarse/few. 0..1.
    #[serde(default = "default_pig_scale")]
    pub pig_scale: f32,
    /// Contrast: soft gradient (0) → crisp hard-edged pattern (1). 0..1.
    #[serde(default = "default_pig_contrast")]
    pub pig_contrast: f32,
    /// Feature density along the coil (reaction speed → spacing over growth). 0..1.
    #[serde(default = "default_pig_density")]
    pub pig_density: f32,
    /// Obliqueness: travelling-wave drift around the lip → diagonal lean. 0..1.
    #[serde(default)]
    pub pig_angle: f32,
    /// Irregularity: seeded noise in the pattern (0 = perfectly regular). 0..1.
    #[serde(default)]
    pub pig_irregularity: f32,

    /// Tessellation: segments per revolution along the coil.
    #[serde(default = "default_seg_theta")]
    pub seg_theta: u32,
    /// Tessellation: segments around the aperture cross-section.
    #[serde(default = "default_seg_phi")]
    pub seg_phi: u32,
}

fn default_aspect() -> f32 {
    1.0
}
fn default_pig_scale() -> f32 {
    0.5
}
fn default_pig_contrast() -> f32 {
    0.5
}
fn default_pig_density() -> f32 {
    0.5
}
fn default_seg_theta() -> u32 {
    96
}
fn default_seg_phi() -> u32 {
    48
}

impl Default for ShellParams {
    fn default() -> Self {
        Self {
            w: 2.0,
            d: 0.15,
            t: 1.5,
            n: 5.0,
            aspect: 1.0,
            rib_ax_count: 0.0,
            rib_ax_amp: 0.0,
            rib_sp_count: 0.0,
            rib_sp_amp: 0.0,
            rib_sharp: 0.0,
            proj_count: 0.0,
            proj_rows: 0.0,
            proj_pos: 0.0,
            proj_size: 0.0,
            proj_sharp: 0.0,
            varix_count: 0.0,
            varix_amp: 0.0,
            seed: 0.0,
            jitter: 0.0,
            pig_regime: 0.0,
            pig_scale: 0.5,
            pig_contrast: 0.5,
            pig_density: 0.5,
            pig_angle: 0.0,
            pig_irregularity: 0.0,
            seg_theta: 96,
            seg_phi: 48,
        }
    }
}

/// Metadata for one user-facing shape parameter — the single source of truth
/// for its valid range, slider configuration, and clamping behaviour.
///
/// The web UI reads this table (via the wasm `param_ranges()` export) to
/// configure its sliders, and `generate` clamps every input to it, so a value
/// can never be out of range regardless of where it came from.
#[derive(Debug, Clone, Serialize)]
pub struct ParamRange {
    /// `ShellParams` field name (e.g. `"rib_ax_count"`). MUST match exactly.
    pub key: &'static str,
    /// Human-readable label for the UI slider.
    pub label: &'static str,
    pub min: f32,
    pub max: f32,
    pub step: f32,
    pub default: f32,
    /// Integer-valued: clamping rounds to the nearest integer; the UI shows no
    /// decimals.
    pub integer: bool,
}

/// The 19 user-facing shape parameters, in UI display order. This is the single
/// source of truth for every parameter's range.
///
/// Bounds are chosen to span the real diversity of **coiled** shells (Raup 1966
/// morphospace + malacology): augers/*Turritella* reach ~20 whorls, open coils
/// reach D≈0.95, spiny *Murex* and fine spiral cords push the ornament counts.
/// The degenerate high-W limpet/single-bivalve-valve case is intentionally out
/// of scope. `seg_theta`/`seg_phi` are absent — they are internal and
/// auto-derived from the ornament frequency, not user parameters.
#[rustfmt::skip] // hand-aligned table — the single source of truth, kept scannable
pub const PARAM_RANGES: &[ParamRange] = &[
    // --- Layer 1: coiling geometry ---
    ParamRange { key: "w",            label: "Whorl expansion W",       min: 1.05, max: 8.0,    step: 0.01, default: 2.0,  integer: false },
    ParamRange { key: "d",            label: "Openness D",              min: 0.0,  max: 0.95,   step: 0.01, default: 0.15, integer: false },
    ParamRange { key: "t",            label: "Translation T",           min: 0.0,  max: 12.0,   step: 0.01, default: 1.5,  integer: false },
    ParamRange { key: "n",            label: "Whorls n",                min: 0.5,  max: 20.0,   step: 0.1,  default: 5.0,  integer: false },
    ParamRange { key: "aspect",       label: "Aperture aspect",         min: 0.3,  max: 4.0,    step: 0.01, default: 1.0,  integer: false },
    // --- Layer 2: ribs / cords / waves ---
    ParamRange { key: "rib_ax_count", label: "Axial ribs / waves",      min: 0.0,  max: 40.0,   step: 1.0,  default: 0.0,  integer: true  },
    ParamRange { key: "rib_ax_amp",   label: "Axial amplitude",         min: 0.0,  max: 0.6,    step: 0.01, default: 0.0,  integer: false },
    ParamRange { key: "rib_sp_count", label: "Spiral cords",            min: 0.0,  max: 60.0,   step: 1.0,  default: 0.0,  integer: true  },
    ParamRange { key: "rib_sp_amp",   label: "Spiral amplitude",        min: 0.0,  max: 0.6,    step: 0.01, default: 0.0,  integer: false },
    ParamRange { key: "rib_sharp",    label: "Profile (wave → ridge)",  min: 0.0,  max: 1.0,    step: 0.01, default: 0.0,  integer: false },
    // --- projections (nodules → spines) ---
    ParamRange { key: "proj_count",   label: "Projections / whorl",     min: 0.0,  max: 30.0,   step: 1.0,  default: 0.0,  integer: true  },
    ParamRange { key: "proj_rows",    label: "Rows around aperture",    min: 0.0,  max: 5.0,    step: 1.0,  default: 0.0,  integer: true  },
    ParamRange { key: "proj_pos",     label: "Row position (φ)",        min: 0.0,  max: TAU,    step: 0.01, default: 0.0,  integer: false },
    ParamRange { key: "proj_size",    label: "Size",                    min: 0.0,  max: 1.2,    step: 0.01, default: 0.0,  integer: false },
    ParamRange { key: "proj_sharp",   label: "Sharpness (bead → needle)", min: 0.0, max: 1.0,   step: 0.01, default: 0.0,  integer: false },
    // --- varices ---
    ParamRange { key: "varix_count",  label: "Varices / whorl",         min: 0.0,  max: 6.0,    step: 1.0,  default: 0.0,  integer: true  },
    ParamRange { key: "varix_amp",    label: "Varix prominence",        min: 0.0,  max: 0.5,    step: 0.01, default: 0.0,  integer: false },
    // --- randomness ---
    ParamRange { key: "seed",         label: "Seed",                    min: 0.0,  max: 9999.0, step: 1.0,  default: 0.0,  integer: true  },
    ParamRange { key: "jitter",       label: "Jitter",                  min: 0.0,  max: 1.0,    step: 0.01, default: 0.0,  integer: false },
];

/// Layer-3 pigmentation parameters, exposed to the UI separately from the shape
/// table (they drive the reaction–diffusion engine, not the geometry). Same
/// `ParamRange` contract and single-source-of-truth role as [`PARAM_RANGES`];
/// `clamp_in_place` clamps these too. The palette/material (Layer 4) is applied
/// viewer-side and is intentionally not here.
#[rustfmt::skip] // hand-aligned table — kept scannable, mirrors PARAM_RANGES
pub const PIGMENT_RANGES: &[ParamRange] = &[
    ParamRange { key: "pig_regime",       label: "Pattern",      min: 0.0, max: 6.0, step: 1.0,  default: 0.0, integer: true  },
    ParamRange { key: "pig_scale",        label: "Feature scale", min: 0.0, max: 1.0, step: 0.01, default: 0.5, integer: false },
    ParamRange { key: "pig_contrast",     label: "Contrast",     min: 0.0, max: 1.0, step: 0.01, default: 0.5, integer: false },
    ParamRange { key: "pig_density",      label: "Density",      min: 0.0, max: 1.0, step: 0.01, default: 0.5, integer: false },
    ParamRange { key: "pig_angle",        label: "Obliqueness",  min: 0.0, max: 1.0, step: 0.01, default: 0.0, integer: false },
    ParamRange { key: "pig_irregularity", label: "Irregularity", min: 0.0, max: 1.0, step: 0.01, default: 0.0, integer: false },
];

impl ShellParams {
    /// Clamp every user-facing field to its `PARAM_RANGES` bound, rounding the
    /// integer-valued fields. `seg_theta`/`seg_phi` are left untouched (internal,
    /// auto-derived). After this, every shape field is guaranteed in range.
    pub fn clamp_in_place(&mut self) {
        fn fix(v: f32, r: &ParamRange) -> f32 {
            let c = v.clamp(r.min, r.max);
            if r.integer {
                c.round()
            } else {
                c
            }
        }
        // Panics only if a range table is missing a key — caught by the unit
        // tests `param_table_covers_every_field` / `pigment_table_is_wellformed`,
        // so it can never reach production.
        let g = |k| {
            PARAM_RANGES
                .iter()
                .chain(PIGMENT_RANGES.iter())
                .find(|r| r.key == k)
                .expect("missing range-table key")
        };
        self.w = fix(self.w, g("w"));
        self.d = fix(self.d, g("d"));
        self.t = fix(self.t, g("t"));
        self.n = fix(self.n, g("n"));
        self.aspect = fix(self.aspect, g("aspect"));
        self.rib_ax_count = fix(self.rib_ax_count, g("rib_ax_count"));
        self.rib_ax_amp = fix(self.rib_ax_amp, g("rib_ax_amp"));
        self.rib_sp_count = fix(self.rib_sp_count, g("rib_sp_count"));
        self.rib_sp_amp = fix(self.rib_sp_amp, g("rib_sp_amp"));
        self.rib_sharp = fix(self.rib_sharp, g("rib_sharp"));
        self.proj_count = fix(self.proj_count, g("proj_count"));
        self.proj_rows = fix(self.proj_rows, g("proj_rows"));
        self.proj_pos = fix(self.proj_pos, g("proj_pos"));
        self.proj_size = fix(self.proj_size, g("proj_size"));
        self.proj_sharp = fix(self.proj_sharp, g("proj_sharp"));
        self.varix_count = fix(self.varix_count, g("varix_count"));
        self.varix_amp = fix(self.varix_amp, g("varix_amp"));
        self.seed = fix(self.seed, g("seed"));
        self.jitter = fix(self.jitter, g("jitter"));
        self.pig_regime = fix(self.pig_regime, g("pig_regime"));
        self.pig_scale = fix(self.pig_scale, g("pig_scale"));
        self.pig_contrast = fix(self.pig_contrast, g("pig_contrast"));
        self.pig_density = fix(self.pig_density, g("pig_density"));
        self.pig_angle = fix(self.pig_angle, g("pig_angle"));
        self.pig_irregularity = fix(self.pig_irregularity, g("pig_irregularity"));
    }

    /// A clamped copy — see [`ShellParams::clamp_in_place`].
    pub fn clamped(&self) -> ShellParams {
        let mut p = self.clone();
        p.clamp_in_place();
        p
    }
}
